name: Docker Build

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    name: Docker Build & Push
    uses: selisebt/workflows/.github/workflows/simeple-docker-build.yaml@main
    secrets: inherit